@echo off
REM ============================================
REM PE Loader Build Script (Windows)
REM Complete workflow: Encode + Build
REM ============================================

echo [*] PE Loader - Complete Build Script
echo [*] ============================================
echo.

REM ============================================
REM Step 1: Check Prerequisites
REM ============================================

echo [*] Step 1: Checking prerequisites...

where python >nul 2>&1
if errorlevel 1 (
    echo [!] Error: Python not found in PATH
    exit /b 1
)

where ghc >nul 2>&1
if errorlevel 1 (
    echo [!] Error: GHC not found in PATH
    exit /b 1
)

if not exist "Main.hs" (
    echo [!] Error: Main.hs not found
    exit /b 1
)

if not exist "Base45.hs" (
    echo [!] Error: Base45.hs not found
    exit /b 1
)

echo [*] Prerequisites satisfied.
echo.

REM ============================================
REM Step 2: Get Target PE File to Obfuscate
REM ============================================

if "%~1"=="" (
    set /p TARGET_PE="Enter PE file path to obfuscate: "
) else (
    set TARGET_PE=%~1
)

if not exist "%TARGET_PE%" (
    echo [!] Error: File not found: %TARGET_PE%
    exit /b 1
)

echo [*] Target PE for obfuscation: %TARGET_PE%
echo.

REM ============================================
REM Step 3: Obfuscate PE File with encoder.py
REM ============================================

echo [*] Step 3: Obfuscating PE file using encoder.py...
set PAYLOAD_BIN=payload.bin

REM Ensure clean slate for payload.bin
if exist "%PAYLOAD_BIN%" del /Q %PAYLOAD_BIN%

python encoder.py "%TARGET_PE%" "%PAYLOAD_BIN%" --xor-key "comp340659"

if errorlevel 1 (
    echo [!] Obfuscation failed with encoder.py
    exit /b 1
)

if not exist "%PAYLOAD_BIN%" (
    echo [!] Error: %PAYLOAD_BIN% was not generated by encoder.py
    exit /b 1
)

echo [*] Obfuscation successful (%PAYLOAD_BIN% created)
echo.

REM ============================================
REM Step 4: Build Haskell Loader
REM ============================================

echo [*] Step 4: Building Haskell loader...
set LOADER_EXE_NAME=loader.exe

REM Clean up previous build artifacts
if exist "%LOADER_EXE_NAME%" del /Q %LOADER_EXE_NAME%
if exist "Main.o" del /Q Main.o
if exist "Main.hi" del /Q Main.hi
if exist "Base45.o" del /Q Base45.o
if exist "Base45.hi" del /Q Base45.hi

ghc -O2 +RTS -K256M -RTS -package bytestring Main.hs Base45.hs -o %LOADER_EXE_NAME%

if errorlevel 1 (
    echo [!] Haskell loader build failed
    exit /b 1
)

echo [*] Haskell loader built successfully as %LOADER_EXE_NAME%
echo.

echo [*] ============================================
echo [*] BUILD COMPLETE
echo [*] ============================================
echo.

echo Would you like to run the generated loader now? (Y/N)
set /p RUN_NOW="Run loader? "
if /i "%RUN_NOW%"=="Y" (
    "%LOADER_EXE_NAME%"
)